name: Keepalive

on:
  schedule:
    - cron: '0 13 4 * *' # Run once a month at midnight
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  keepalive-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit Empty Change
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keepalive to prevent 60-day inactivity"
          git push
